name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install SSH and SCP
        run: |
          apt-get update
          apt-get install -y ssh-client

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean Droplet
        run: |
          scp -r ./* ${{ secrets.USER }}@${{ secrets.SERVER }}:${{ secrets.PATH }}
          ssh ${{ secrets.USER }}@${{ secrets.SERVER }} <<EOF
            cd ${{ secrets.PATH }}
            source ~/.bashrc
            source ${{ secrets.NVM_PATH }}/nvm.sh
            echo "19.3.0" > .nvmrc
            nvm use
            chmod +x scripts/setup_env.sh
            bash scripts/setup_env.sh
            ${{ secrets.NODE_PATH }}/npm install
            ls
            ${{ secrets.NODE_PATH }}/pm2 restart server.js
          EOF
